In [7]:
import numpy as np
from scipy.interpolate import interp1d

hajonta=np.zeros((100,3))

In [ ]:
 0,82707 	 1,02568 	 1,26636 
 0,82596 	 1,02855 	 1,34849 
 0,77539 	 1,03629 	 1,44658 
		
		
		
0,729356592	1,053135396	1,698384385

In [39]:
#hajonta[20,:]=[0.82707,1.02568,1.26636]
#hajonta[25,:]=[0.82596,1.02855,1.34849 ]
#hajonta[30,:]=[0.77539,1.03629,1.44658 ]
#hajonta[50,:]=[0.729356592,1.053135396,1.698384385 ]

hajonta[20,:]=[0.81436,1.00992,1.24690]
hajonta[25,:]=[0.81481,1.01466,1.33027 ]
hajonta[30,:]=[0.75011,1.00251,1.39943 ]
hajonta[50,:]=[0.637910872,0.921094739,1.485443303 ]

In [40]:
def ifunc(x1,x2,hajonta,q):
    x = np.array([x1,x2])
    y = np.array([hajonta[x1,q],hajonta[x2,q]])
    f = interp1d(x, y)
    x2 = np.linspace(x1, x2, num=x2-x1, endpoint=True)
        
    return f(x2)

In [41]:
for q in range(3):
    hajonta[20:25,q]=ifunc(20,25,hajonta,q)
    hajonta[25:30,q]=ifunc(25,30,hajonta,q)    
    hajonta[30:50,q]=ifunc(30,50,hajonta,q)
    hajonta[51:100,q]=hajonta[50,q]

In [42]:
print(hajonta[20:72,:])

[[0.81436    1.00992    1.2469    ]
 [0.8144725  1.011105   1.2677425 ]
 [0.814585   1.01229    1.288585  ]
 [0.8146975  1.013475   1.3094275 ]
 [0.81481    1.01466    1.33027   ]
 [0.81481    1.01466    1.33027   ]
 [0.798635   1.0116225  1.34756   ]
 [0.78246    1.008585   1.36485   ]
 [0.766285   1.0055475  1.38214   ]
 [0.75011    1.00251    1.39943   ]
 [0.75011    1.00251    1.39943   ]
 [0.74420478 0.99822499 1.40395702]
 [0.73829957 0.99393997 1.40848403]
 [0.73239435 0.98965496 1.41301105]
 [0.72648913 0.98536995 1.41753806]
 [0.72058391 0.98108493 1.42206508]
 [0.7146787  0.97679992 1.4265921 ]
 [0.70877348 0.9725149  1.43111911]
 [0.70286826 0.96822989 1.43564613]
 [0.69696304 0.96394488 1.44017314]
 [0.69105783 0.95965986 1.44470016]
 [0.68515261 0.95537485 1.44922718]
 [0.67924739 0.95108984 1.45375419]
 [0.67334218 0.94680482 1.45828121]
 [0.66743696 0.94251981 1.46280822]
 [0.66153174 0.93823479 1.46733524]
 [0.65562652 0.93394978 1.47186226]
 [0.64972131 0.92966477 1.47