In [7]:
import numpy as np
from scipy.interpolate import interp1d

hajonta=np.zeros((100,3))

In [ ]:
 0,82707 	 1,02568 	 1,26636 
 0,82596 	 1,02855 	 1,34849 
 0,77539 	 1,03629 	 1,44658 
		
		
		
0,729356592	1,053135396	1,698384385

In [34]:
hajonta[20,:]=[0.82707,1.02568,1.26636]
hajonta[25,:]=[0.82596,1.02855,1.34849 ]
hajonta[30,:]=[0.77539,1.03629,1.44658 ]
hajonta[50,:]=[0.729356592,1.053135396,1.698384385 ]


In [35]:
def ifunc(x1,x2,hajonta,q):
    x = np.array([x1,x2])
    y = np.array([hajonta[x1,q],hajonta[x2,q]])
    f = interp1d(x, y)
    x2 = np.linspace(x1, x2, num=x2-x1, endpoint=True)
        
    return f(x2)

In [36]:
for q in range(3):
    hajonta[20:25,q]=ifunc(20,25,hajonta,q)
    hajonta[25:30,q]=ifunc(25,30,hajonta,q)    
    hajonta[30:50,q]=ifunc(30,50,hajonta,q)
    hajonta[51:100,q]=hajonta[50,q]

In [38]:
print(hajonta[20:70,:])

[[0.82707    1.02568    1.26636   ]
 [0.8267925  1.0263975  1.2868925 ]
 [0.826515   1.027115   1.307425  ]
 [0.8262375  1.0278325  1.3279575 ]
 [0.82596    1.02855    1.34849   ]
 [0.82596    1.02855    1.34849   ]
 [0.8133175  1.030485   1.3730125 ]
 [0.800675   1.03242    1.397535  ]
 [0.7880325  1.034355   1.4220575 ]
 [0.77539    1.03629    1.44658   ]
 [0.77539    1.03629    1.44658   ]
 [0.77296719 1.0371766  1.45983286]
 [0.77054438 1.0380632  1.47308572]
 [0.76812157 1.0389498  1.48633859]
 [0.76569876 1.0398364  1.49959145]
 [0.76327595 1.040723   1.51284431]
 [0.76085313 1.0416096  1.52609717]
 [0.75843032 1.0424962  1.53935004]
 [0.75600751 1.0433828  1.5526029 ]
 [0.7535847  1.0442694  1.56585576]
 [0.75116189 1.045156   1.57910862]
 [0.74873908 1.0460426  1.59236149]
 [0.74631627 1.0469292  1.60561435]
 [0.74389346 1.0478158  1.61886721]
 [0.74147065 1.0487024  1.63212007]
 [0.73904784 1.049589   1.64537294]
 [0.73662502 1.0504756  1.6586258 ]
 [0.73420221 1.0513622  1.67